'use strict';
const $=id=>document.getElementById(id);let expanded=false,busy=false,previous=[],lastMove=0,volumeTimer,chordSince=0,chordLatched=false;
const controls=()=>[$('resume'),$('volume'),$('quality'),$('end')].filter(e=>!e.disabled);
function error(e){$('error').hidden=false;$('error').textContent=e.message;}
window.orbitSession.onState(state=>{const opening=state.expanded&&!expanded;expanded=state.expanded;busy=state.busy;$('title').textContent=state.title;$('controls').hidden=!expanded;$('description').textContent=state.game?'Closing here also closes the game on Zeiron.':'End Desktop to return to your Orbit library.';$('end').textContent=state.game?'Close game':'End Desktop';for(const id of ['menu','resume','end','quality','cancel','confirm-end'])$(id).disabled=busy;$('quality').value=state.profile||'balanced';$('quality-note').textContent='Playing in '+(state.activeProfile||state.profile||'balanced')+'. Changes apply when you start your next session.';const audio=state.audio;$('volume').disabled=busy||!audio?.available;if(audio?.available){$('volume').value=audio.percent;$('level').textContent=audio.muted?'Muted':audio.percent+'%';$('audio-note').textContent='Changes only this stream’s audio.';}else{$('audio-note').textContent=audio?.reason||'Checking stream audio…';}if(opening){$('confirm').hidden=true;$('error').hidden=true;requestAnimationFrame(()=>$('resume').focus());}if(!expanded){$('confirm').hidden=true;clearTimeout(volumeTimer);}});
$('menu').onclick=()=>window.orbitSession.menu().catch(error);$('resume').onclick=()=>window.orbitSession.resume().catch(error);
$('end').onclick=()=>{$('confirm').hidden=false;$('cancel').focus();};$('cancel').onclick=()=>{$('confirm').hidden=true;$('end').focus();};$('confirm-end').onclick=async()=>{try{await window.orbitSession.end();}catch(e){error(e);$('confirm').hidden=true;$('resume').focus();}};
$('volume').oninput=()=>{$('level').textContent=$('volume').value+'%';clearTimeout(volumeTimer);volumeTimer=setTimeout(()=>{if(expanded)window.orbitSession.volume(Number($('volume').value)).catch(error);},250);};$('quality').onchange=()=>window.orbitSession.quality($('quality').value).catch(error);
function back(){if(!$('confirm').hidden)$('cancel').click();else window.orbitSession.resume().catch(error);}
function move(delta){const items=$('confirm').hidden?controls():[$('cancel'),$('confirm-end')];let i=items.indexOf(document.activeElement);items[(i+delta+items.length)%items.length]?.focus();}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();back();}if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();move(e.key==='ArrowUp'?-1:1);}});
function poll(){const pad=[...navigator.getGamepads()].find(p=>p?.connected);if(pad){const buttons=pad.buttons.map(b=>b.pressed);if(buttons[8]&&buttons[9]){if(!chordSince)chordSince=performance.now();if(!expanded&&!chordLatched&&performance.now()-chordSince>700){chordLatched=true;window.orbitSession.menu().catch(error);}}else{chordSince=0;chordLatched=false;}if(expanded&&!busy&&document.hasFocus()){if(buttons[1]&&!previous[1])back();else if(buttons[0]&&!previous[0]&&document.activeElement?.tagName==='BUTTON')document.activeElement.click();const now=performance.now();if(now-lastMove>220){if(buttons[12]||pad.axes[1]<-.6){move(-1);lastMove=now;}else if(buttons[13]||pad.axes[1]>.6){move(1);lastMove=now;}else if(buttons[14]||buttons[15]||Math.abs(pad.axes[0])>.6){const delta=buttons[14]||pad.axes[0]<-.6?-1:1;const el=document.activeElement;if(el===$('volume')){el.value=Number(el.value)+delta*5;el.dispatchEvent(new Event('input'));}if(el===$('quality')){el.selectedIndex=Math.max(0,Math.min(2,el.selectedIndex+delta));el.dispatchEvent(new Event('change'));}lastMove=now;}}}previous=buttons;}else previous=[];requestAnimationFrame(poll);}poll();
