'use strict';
const $=id=>document.getElementById(id);let expanded=false,busy=false,streaming=false,previous=[],lastMove=0,chordSince=0,chordLatched=false,tab='device',latestState;const timers=new Map(),pending=new Set();
const controls=()=>['tab-device','tab-stream','device-volume','brightness','device-refresh','volume','quality','resume','end'].map($).filter(e=>!e.disabled&&e.getClientRects().length);
function error(e){$('error').hidden=false;$('error').textContent=e.message;}
function pane(name,focus=false){tab=name;for(const id of ['device','stream']){$(id+'-settings').hidden=id!==name;$('tab-'+id).setAttribute('aria-selected',String(id===name));}if(focus)$('tab-'+name).focus();}
function slider(id,label,state,note,fallback,disabled){$(id).disabled=disabled||!state?.available;if(state?.available){if(!pending.has(id)){const value=String(state.percent);if($(id).value!==value)$(id).value=value;$(label).textContent=state.muted?'Muted':value+'%';}$(note).textContent=id==='brightness'?'Adjusts this device’s built-in display.':id==='device-volume'?'All sound on this device.':'Changes only this stream’s audio.';}else{$(label).textContent='—';$(note).textContent=state?.reason||fallback;}}
function renderState(state){latestState=state;
 const opening=state.expanded&&!expanded;expanded=state.expanded;busy=state.busy;streaming=state.streaming;$('title').textContent=state.title;$('mode').textContent=streaming?(state.game?'NOW PLAYING':'DESKTOP MODE'):'QUICK SETTINGS';$('confirm-label').textContent=state.game?'Close this game on Zeiron?':'End '+state.title+' and return to Orbit?';$('confirm-end').textContent=state.game?'Close game':'End session';$('controls').hidden=!expanded;$('description').textContent=streaming?(state.game?'Closing here also closes the game on Zeiron.':'End this session to return to Orbit. Apps stay open on Zeiron.'):'Handheld controls here. Games and apps run on Zeiron.';$('end').textContent=state.game?'Close game':'End '+state.title;$('end').hidden=!streaming;$('resume').textContent=streaming?'Resume · B':'Back to Orbit · B';
 for(const id of ['menu','resume','end','quality','cancel','confirm-end','tab-device','tab-stream'])$(id).disabled=busy;$('device-refresh').disabled=busy||state.deviceBusy||state.deviceUpdating;$('device-refresh').textContent=state.deviceUpdating?'Updating device status…':'Refresh device status';
 const d=state.device,b=d?.battery,w=d?.wifi;$('battery').textContent=b?.available?b.percent+'%'+(b.pluggedIn?' · plugged in':' · on battery'):b?.reason||(state.deviceUpdating?'Checking…':'Unavailable');$('wifi').textContent=w?.available?w.status:w?.reason||(state.deviceUpdating?'Checking…':'Unavailable');$('device-name').textContent=d?.deviceName?d.deviceName+' · controls affect this device.':state.deviceError||'Controls on this device, separate from Zeiron.';
 slider('device-volume','device-level',d?.volume,'device-audio-note','Device volume unavailable',busy||state.deviceBusy);slider('brightness','brightness-level',d?.brightness,'brightness-note','Brightness unavailable on this device',busy||state.deviceBusy);slider('volume','level',state.audio,'audio-note',streaming?'Checking stream audio…':'Start a stream to adjust stream volume.',busy||!streaming);
 $('quality').value=state.profile||'balanced';$('quality-note').textContent=streaming?'Streaming in '+(state.activeProfile||state.profile||'balanced')+'. Changes apply to your next session.':'This quality will be used for your next session.';const stream=state.stream;$('stream-summary').textContent=streaming?stream.resolution.replace('x',' × ')+' · target '+stream.fps+' fps · '+stream.bitrateMbps+' Mbps'+(Number.isFinite(stream.hostResponseMs)?' · host response '+stream.hostResponseMs+' ms':''):'No active stream. Your handheld settings work without Zeiron.';
 if(opening){pane('device');$('confirm').hidden=true;$('error').hidden=true;requestAnimationFrame(()=>$('resume').focus());}if(!expanded){$('confirm').hidden=true;for(const t of timers.values())clearTimeout(t);timers.clear();pending.clear();}
}
window.orbitSession.onState(renderState);
$('menu').onclick=()=>window.orbitSession.menu().catch(error);$('resume').onclick=()=>window.orbitSession.resume().catch(error);$('tab-device').onclick=()=>pane('device');$('tab-stream').onclick=()=>pane('stream');$('device-refresh').onclick=()=>window.orbitSession.device().catch(error);
$('end').onclick=()=>{$('confirm').hidden=false;$('cancel').focus();};$('cancel').onclick=()=>{$('confirm').hidden=true;$('end').focus();};$('confirm-end').onclick=async()=>{try{await window.orbitSession.end();}catch(e){error(e);$('confirm').hidden=true;$('resume').focus();}};
for(const [id,label,method] of [['volume','level','volume'],['device-volume','device-level','deviceVolume'],['brightness','brightness-level','brightness']])$(id).oninput=()=>{const level=Number($(id).value);$(label).textContent=level+'%';pending.add(id);clearTimeout(timers.get(id));timers.set(id,setTimeout(async()=>{if(!expanded){pending.delete(id);return;}try{await window.orbitSession[method](level);}catch(e){error(e);}finally{pending.delete(id);timers.delete(id);if(latestState)renderState(latestState);}},350));};
$('quality').onchange=()=>window.orbitSession.quality($('quality').value).catch(error);
function back(){if(!$('confirm').hidden)$('cancel').click();else window.orbitSession.resume().catch(error);}
function move(delta){const items=$('confirm').hidden?controls():[$('cancel'),$('confirm-end')];let i=items.indexOf(document.activeElement);items[(i+delta+items.length)%items.length]?.focus();}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();back();}if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();move(e.key==='ArrowUp'?-1:1);}});
function poll(){const pad=[...navigator.getGamepads()].find(p=>p?.connected);if(pad){const buttons=pad.buttons.map(b=>b.pressed);if(buttons[8]&&buttons[9]){if(!chordSince)chordSince=performance.now();if(streaming&&!expanded&&!chordLatched&&performance.now()-chordSince>700){chordLatched=true;window.orbitSession.menu().catch(error);}}else{chordSince=0;chordLatched=false;}
 if(expanded&&!busy&&document.hasFocus()){
  if(buttons[1]&&!previous[1])back();else if(buttons[0]&&!previous[0]&&document.activeElement?.tagName==='BUTTON')document.activeElement.click();if((buttons[4]&&!previous[4])||(buttons[5]&&!previous[5]))pane(tab==='device'?'stream':'device',true);
  const now=performance.now();if(now-lastMove>220){if(buttons[12]||pad.axes[1]<-.6){move(-1);lastMove=now;}else if(buttons[13]||pad.axes[1]>.6){move(1);lastMove=now;}else if(buttons[14]||buttons[15]||Math.abs(pad.axes[0])>.6){const delta=buttons[14]||pad.axes[0]<-.6?-1:1,el=document.activeElement;if(el?.type==='range'&&!el.disabled){el.value=Number(el.value)+delta*5;el.dispatchEvent(new Event('input'));}if(el===$('quality')){el.selectedIndex=Math.max(0,Math.min(2,el.selectedIndex+delta));el.dispatchEvent(new Event('change'));}lastMove=now;}}
 }previous=buttons;}else previous=[];requestAnimationFrame(poll);}poll();
